version: 0.2

phases:
  install:
    commands:
      - cd workshop2/image-uploader
      - npm install
  build:
    commands:
      - npm run build  # Builds the project
artifacts:
  files:
    - '**/*'
  base-directory: workshop2/image-uploader/build  # Directory with output files (e.g., React app)
